CONFIG_PIC64GX_HAL_LAST_HART=4
CONFIG_SGMII_SUPPORT=y
CONFIG_DDR_SUPPORT=y
CONFIG_MSSIO_SUPPORT=y
CONFIG_MEMORY="lim"
CONFIG_APPLICATION_STACK_SIZE=8192
CONFIG_APPLICATION_HEAP_SIZE=8192
CONFIG_APPLICATION_RAM_SIZE=32768
CONFIG_PLATFORM_MSS=y
CONFIG_PLATFORM=y
CONFIG_MSS_MMUART=y
